// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCar29XVLtA3yPqwezzGUV-G5soFOzMdkU',
    appId: '1:824468501954:web:d800fc09441fe954c8d25b',
    messagingSenderId: '824468501954',
    projectId: 'sahabatbk-f3fb9',
    authDomain: 'sahabatbk-f3fb9.firebaseapp.com',
    storageBucket: 'sahabatbk-f3fb9.firebasestorage.app',
    measurementId: 'G-MDYN7ZDK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPdwGf51r3ioZPXFRqC7Zsao-hN7h96I',
    appId: '1:824468501954:android:751031e1cc19f2fec8d25b',
    messagingSenderId: '824468501954',
    projectId: 'sahabatbk-f3fb9',
    storageBucket: 'sahabatbk-f3fb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_IkbwYPktOeyu2-eKf1srK23yWDFjJ4',
    appId: '1:824468501954:ios:d3b68d02ad82f56cc8d25b',
    messagingSenderId: '824468501954',
    projectId: 'sahabatbk-f3fb9',
    storageBucket: 'sahabatbk-f3fb9.firebasestorage.app',
    iosBundleId: 'com.example.sahabatbk',
  );

}